# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-11.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-11.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-11.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/david/development/ext/src/cegui-deps-0.8.x-src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/david/development/ext/src/cegui-deps-0.8.x-src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-11.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-11.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/david/development/ext/src/cegui-deps-0.8.x-src/CMakeFiles /Users/david/development/ext/src/cegui-deps-0.8.x-src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/david/development/ext/src/cegui-deps-0.8.x-src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named POST_BUILD_CLEANUP

# Build rule for target.
POST_BUILD_CLEANUP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 POST_BUILD_CLEANUP
.PHONY : POST_BUILD_CLEANUP

# fast build rule for target.
POST_BUILD_CLEANUP/fast:
	$(MAKE) -f CMakeFiles/POST_BUILD_CLEANUP.dir/build.make CMakeFiles/POST_BUILD_CLEANUP.dir/build
.PHONY : POST_BUILD_CLEANUP/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f src/zlib-1.2.5/CEGUI-BUILD/CMakeFiles/zlib.dir/build.make src/zlib-1.2.5/CEGUI-BUILD/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named zlib_static

# Build rule for target.
zlib_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib_static
.PHONY : zlib_static

# fast build rule for target.
zlib_static/fast:
	$(MAKE) -f src/zlib-1.2.5/CEGUI-BUILD/CMakeFiles/zlib_static.dir/build.make src/zlib-1.2.5/CEGUI-BUILD/CMakeFiles/zlib_static.dir/build
.PHONY : zlib_static/fast

#=============================================================================
# Target rules for targets named libpng

# Build rule for target.
libpng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpng
.PHONY : libpng

# fast build rule for target.
libpng/fast:
	$(MAKE) -f src/libpng-1.4.7/CEGUI-BUILD/CMakeFiles/libpng.dir/build.make src/libpng-1.4.7/CEGUI-BUILD/CMakeFiles/libpng.dir/build
.PHONY : libpng/fast

#=============================================================================
# Target rules for targets named libpng_static

# Build rule for target.
libpng_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpng_static
.PHONY : libpng_static

# fast build rule for target.
libpng_static/fast:
	$(MAKE) -f src/libpng-1.4.7/CEGUI-BUILD/CMakeFiles/libpng_static.dir/build.make src/libpng-1.4.7/CEGUI-BUILD/CMakeFiles/libpng_static.dir/build
.PHONY : libpng_static/fast

#=============================================================================
# Target rules for targets named jpeg

# Build rule for target.
jpeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jpeg
.PHONY : jpeg

# fast build rule for target.
jpeg/fast:
	$(MAKE) -f src/jpeg-8c/CEGUI-BUILD/CMakeFiles/jpeg.dir/build.make src/jpeg-8c/CEGUI-BUILD/CMakeFiles/jpeg.dir/build
.PHONY : jpeg/fast

#=============================================================================
# Target rules for targets named jpeg_static

# Build rule for target.
jpeg_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jpeg_static
.PHONY : jpeg_static

# fast build rule for target.
jpeg_static/fast:
	$(MAKE) -f src/jpeg-8c/CEGUI-BUILD/CMakeFiles/jpeg_static.dir/build.make src/jpeg-8c/CEGUI-BUILD/CMakeFiles/jpeg_static.dir/build
.PHONY : jpeg_static/fast

#=============================================================================
# Target rules for targets named libmng

# Build rule for target.
libmng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmng
.PHONY : libmng

# fast build rule for target.
libmng/fast:
	$(MAKE) -f src/libmng-1.0.10/CEGUI-BUILD/CMakeFiles/libmng.dir/build.make src/libmng-1.0.10/CEGUI-BUILD/CMakeFiles/libmng.dir/build
.PHONY : libmng/fast

#=============================================================================
# Target rules for targets named libmng_static

# Build rule for target.
libmng_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmng_static
.PHONY : libmng_static

# fast build rule for target.
libmng_static/fast:
	$(MAKE) -f src/libmng-1.0.10/CEGUI-BUILD/CMakeFiles/libmng_static.dir/build.make src/libmng-1.0.10/CEGUI-BUILD/CMakeFiles/libmng_static.dir/build
.PHONY : libmng_static/fast

#=============================================================================
# Target rules for targets named libtiff

# Build rule for target.
libtiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtiff
.PHONY : libtiff

# fast build rule for target.
libtiff/fast:
	$(MAKE) -f src/tiff-3.9.5/CEGUI-BUILD/CMakeFiles/libtiff.dir/build.make src/tiff-3.9.5/CEGUI-BUILD/CMakeFiles/libtiff.dir/build
.PHONY : libtiff/fast

#=============================================================================
# Target rules for targets named libtiff_static

# Build rule for target.
libtiff_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtiff_static
.PHONY : libtiff_static

# fast build rule for target.
libtiff_static/fast:
	$(MAKE) -f src/tiff-3.9.5/CEGUI-BUILD/CMakeFiles/libtiff_static.dir/build.make src/tiff-3.9.5/CEGUI-BUILD/CMakeFiles/libtiff_static.dir/build
.PHONY : libtiff_static/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) -f src/freetype-2.4.4/CEGUI-BUILD/CMakeFiles/freetype.dir/build.make src/freetype-2.4.4/CEGUI-BUILD/CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

#=============================================================================
# Target rules for targets named freetype_static

# Build rule for target.
freetype_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype_static
.PHONY : freetype_static

# fast build rule for target.
freetype_static/fast:
	$(MAKE) -f src/freetype-2.4.4/CEGUI-BUILD/CMakeFiles/freetype_static.dir/build.make src/freetype-2.4.4/CEGUI-BUILD/CMakeFiles/freetype_static.dir/build
.PHONY : freetype_static/fast

#=============================================================================
# Target rules for targets named dftables

# Build rule for target.
dftables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dftables
.PHONY : dftables

# fast build rule for target.
dftables/fast:
	$(MAKE) -f src/pcre-8.12/CEGUI-BUILD/CMakeFiles/dftables.dir/build.make src/pcre-8.12/CEGUI-BUILD/CMakeFiles/dftables.dir/build
.PHONY : dftables/fast

#=============================================================================
# Target rules for targets named pcre

# Build rule for target.
pcre: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcre
.PHONY : pcre

# fast build rule for target.
pcre/fast:
	$(MAKE) -f src/pcre-8.12/CEGUI-BUILD/CMakeFiles/pcre.dir/build.make src/pcre-8.12/CEGUI-BUILD/CMakeFiles/pcre.dir/build
.PHONY : pcre/fast

#=============================================================================
# Target rules for targets named pcre_static

# Build rule for target.
pcre_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcre_static
.PHONY : pcre_static

# fast build rule for target.
pcre_static/fast:
	$(MAKE) -f src/pcre-8.12/CEGUI-BUILD/CMakeFiles/pcre_static.dir/build.make src/pcre-8.12/CEGUI-BUILD/CMakeFiles/pcre_static.dir/build
.PHONY : pcre_static/fast

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) -f src/lua-5.1.4/CEGUI-BUILD/CMakeFiles/lua.dir/build.make src/lua-5.1.4/CEGUI-BUILD/CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named lua_static

# Build rule for target.
lua_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua_static
.PHONY : lua_static

# fast build rule for target.
lua_static/fast:
	$(MAKE) -f src/lua-5.1.4/CEGUI-BUILD/CMakeFiles/lua_static.dir/build.make src/lua-5.1.4/CEGUI-BUILD/CMakeFiles/lua_static.dir/build
.PHONY : lua_static/fast

#=============================================================================
# Target rules for targets named expat

# Build rule for target.
expat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expat
.PHONY : expat

# fast build rule for target.
expat/fast:
	$(MAKE) -f src/expat-2.0.1/CEGUI-BUILD/CMakeFiles/expat.dir/build.make src/expat-2.0.1/CEGUI-BUILD/CMakeFiles/expat.dir/build
.PHONY : expat/fast

#=============================================================================
# Target rules for targets named expat_static

# Build rule for target.
expat_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expat_static
.PHONY : expat_static

# fast build rule for target.
expat_static/fast:
	$(MAKE) -f src/expat-2.0.1/CEGUI-BUILD/CMakeFiles/expat_static.dir/build.make src/expat-2.0.1/CEGUI-BUILD/CMakeFiles/expat_static.dir/build
.PHONY : expat_static/fast

#=============================================================================
# Target rules for targets named xerces-c_3

# Build rule for target.
xerces-c_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xerces-c_3
.PHONY : xerces-c_3

# fast build rule for target.
xerces-c_3/fast:
	$(MAKE) -f src/xerces-c-3.1.1/CEGUI-BUILD/CMakeFiles/xerces-c_3.dir/build.make src/xerces-c-3.1.1/CEGUI-BUILD/CMakeFiles/xerces-c_3.dir/build
.PHONY : xerces-c_3/fast

#=============================================================================
# Target rules for targets named xerces-c_3_static

# Build rule for target.
xerces-c_3_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xerces-c_3_static
.PHONY : xerces-c_3_static

# fast build rule for target.
xerces-c_3_static/fast:
	$(MAKE) -f src/xerces-c-3.1.1/CEGUI-BUILD/CMakeFiles/xerces-c_3_static.dir/build.make src/xerces-c-3.1.1/CEGUI-BUILD/CMakeFiles/xerces-c_3_static.dir/build
.PHONY : xerces-c_3_static/fast

#=============================================================================
# Target rules for targets named SILLY

# Build rule for target.
SILLY: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SILLY
.PHONY : SILLY

# fast build rule for target.
SILLY/fast:
	$(MAKE) -f src/SILLY/CEGUI-BUILD/CMakeFiles/SILLY.dir/build.make src/SILLY/CEGUI-BUILD/CMakeFiles/SILLY.dir/build
.PHONY : SILLY/fast

#=============================================================================
# Target rules for targets named SILLY_static

# Build rule for target.
SILLY_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SILLY_static
.PHONY : SILLY_static

# fast build rule for target.
SILLY_static/fast:
	$(MAKE) -f src/SILLY/CEGUI-BUILD/CMakeFiles/SILLY_static.dir/build.make src/SILLY/CEGUI-BUILD/CMakeFiles/SILLY_static.dir/build
.PHONY : SILLY_static/fast

#=============================================================================
# Target rules for targets named glew

# Build rule for target.
glew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glew
.PHONY : glew

# fast build rule for target.
glew/fast:
	$(MAKE) -f src/glew-1.7.0/CEGUI-BUILD/CMakeFiles/glew.dir/build.make src/glew-1.7.0/CEGUI-BUILD/CMakeFiles/glew.dir/build
.PHONY : glew/fast

#=============================================================================
# Target rules for targets named glew_static

# Build rule for target.
glew_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glew_static
.PHONY : glew_static

# fast build rule for target.
glew_static/fast:
	$(MAKE) -f src/glew-1.7.0/CEGUI-BUILD/CMakeFiles/glew_static.dir/build.make src/glew-1.7.0/CEGUI-BUILD/CMakeFiles/glew_static.dir/build
.PHONY : glew_static/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f src/glfw-2.7.2/CEGUI-BUILD/CMakeFiles/glfw.dir/build.make src/glfw-2.7.2/CEGUI-BUILD/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glfw_static

# Build rule for target.
glfw_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw_static
.PHONY : glfw_static

# fast build rule for target.
glfw_static/fast:
	$(MAKE) -f src/glfw-2.7.2/CEGUI-BUILD/CMakeFiles/glfw_static.dir/build.make src/glfw-2.7.2/CEGUI-BUILD/CMakeFiles/glfw_static.dir/build
.PHONY : glfw_static/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) -f src/glm-0.9.3.1/CEGUI-BUILD/CMakeFiles/glm.dir/build.make src/glm-0.9.3.1/CEGUI-BUILD/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named toluapp

# Build rule for target.
toluapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toluapp
.PHONY : toluapp

# fast build rule for target.
toluapp/fast:
	$(MAKE) -f src/tolua++-1.0.93/CEGUI-BUILD/CMakeFiles/toluapp.dir/build.make src/tolua++-1.0.93/CEGUI-BUILD/CMakeFiles/toluapp.dir/build
.PHONY : toluapp/fast

#=============================================================================
# Target rules for targets named toluapp_static

# Build rule for target.
toluapp_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toluapp_static
.PHONY : toluapp_static

# fast build rule for target.
toluapp_static/fast:
	$(MAKE) -f src/tolua++-1.0.93/CEGUI-BUILD/CMakeFiles/toluapp_static.dir/build.make src/tolua++-1.0.93/CEGUI-BUILD/CMakeFiles/toluapp_static.dir/build
.PHONY : toluapp_static/fast

#=============================================================================
# Target rules for targets named ode

# Build rule for target.
ode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ode
.PHONY : ode

# fast build rule for target.
ode/fast:
	$(MAKE) -f src/ode-0.12/CEGUI-BUILD/CMakeFiles/ode.dir/build.make src/ode-0.12/CEGUI-BUILD/CMakeFiles/ode.dir/build
.PHONY : ode/fast

#=============================================================================
# Target rules for targets named ode_static

# Build rule for target.
ode_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ode_static
.PHONY : ode_static

# fast build rule for target.
ode_static/fast:
	$(MAKE) -f src/ode-0.12/CEGUI-BUILD/CMakeFiles/ode_static.dir/build.make src/ode-0.12/CEGUI-BUILD/CMakeFiles/ode_static.dir/build
.PHONY : ode_static/fast

#=============================================================================
# Target rules for targets named cppunit

# Build rule for target.
cppunit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppunit
.PHONY : cppunit

# fast build rule for target.
cppunit/fast:
	$(MAKE) -f src/cppunit-1.13.1/CEGUI-BUILD/CMakeFiles/cppunit.dir/build.make src/cppunit-1.13.1/CEGUI-BUILD/CMakeFiles/cppunit.dir/build
.PHONY : cppunit/fast

#=============================================================================
# Target rules for targets named cppunit_static

# Build rule for target.
cppunit_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppunit_static
.PHONY : cppunit_static

# fast build rule for target.
cppunit_static/fast:
	$(MAKE) -f src/cppunit-1.13.1/CEGUI-BUILD/CMakeFiles/cppunit_static.dir/build.make src/cppunit-1.13.1/CEGUI-BUILD/CMakeFiles/cppunit_static.dir/build
.PHONY : cppunit_static/fast

#=============================================================================
# Target rules for targets named NL

# Build rule for target.
NL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NL
.PHONY : NL

# fast build rule for target.
NL/fast:
	$(MAKE) -f src/HawkNL1.68/CEGUI-BUILD/CMakeFiles/NL.dir/build.make src/HawkNL1.68/CEGUI-BUILD/CMakeFiles/NL.dir/build
.PHONY : NL/fast

#=============================================================================
# Target rules for targets named NL_static

# Build rule for target.
NL_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NL_static
.PHONY : NL_static

# fast build rule for target.
NL_static/fast:
	$(MAKE) -f src/HawkNL1.68/CEGUI-BUILD/CMakeFiles/NL_static.dir/build.make src/HawkNL1.68/CEGUI-BUILD/CMakeFiles/NL_static.dir/build
.PHONY : NL_static/fast

#=============================================================================
# Target rules for targets named gne

# Build rule for target.
gne: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gne
.PHONY : gne

# fast build rule for target.
gne/fast:
	$(MAKE) -f src/gnelib-0_70/CEGUI-BUILD/CMakeFiles/gne.dir/build.make src/gnelib-0_70/CEGUI-BUILD/CMakeFiles/gne.dir/build
.PHONY : gne/fast

#=============================================================================
# Target rules for targets named gne_static

# Build rule for target.
gne_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gne_static
.PHONY : gne_static

# fast build rule for target.
gne_static/fast:
	$(MAKE) -f src/gnelib-0_70/CEGUI-BUILD/CMakeFiles/gne_static.dir/build.make src/gnelib-0_70/CEGUI-BUILD/CMakeFiles/gne_static.dir/build
.PHONY : gne_static/fast

#=============================================================================
# Target rules for targets named cal3d

# Build rule for target.
cal3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cal3d
.PHONY : cal3d

# fast build rule for target.
cal3d/fast:
	$(MAKE) -f src/cal3d-trunk/CEGUI-BUILD/CMakeFiles/cal3d.dir/build.make src/cal3d-trunk/CEGUI-BUILD/CMakeFiles/cal3d.dir/build
.PHONY : cal3d/fast

#=============================================================================
# Target rules for targets named cal3d_converter

# Build rule for target.
cal3d_converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cal3d_converter
.PHONY : cal3d_converter

# fast build rule for target.
cal3d_converter/fast:
	$(MAKE) -f src/cal3d-trunk/CEGUI-BUILD/CMakeFiles/cal3d_converter.dir/build.make src/cal3d-trunk/CEGUI-BUILD/CMakeFiles/cal3d_converter.dir/build
.PHONY : cal3d_converter/fast

#=============================================================================
# Target rules for targets named cal3d_static

# Build rule for target.
cal3d_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cal3d_static
.PHONY : cal3d_static

# fast build rule for target.
cal3d_static/fast:
	$(MAKE) -f src/cal3d-trunk/CEGUI-BUILD/CMakeFiles/cal3d_static.dir/build.make src/cal3d-trunk/CEGUI-BUILD/CMakeFiles/cal3d_static.dir/build
.PHONY : cal3d_static/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... POST_BUILD_CLEANUP"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... zlib"
	@echo "... zlib_static"
	@echo "... libpng"
	@echo "... libpng_static"
	@echo "... jpeg"
	@echo "... jpeg_static"
	@echo "... libmng"
	@echo "... libmng_static"
	@echo "... libtiff"
	@echo "... libtiff_static"
	@echo "... freetype"
	@echo "... freetype_static"
	@echo "... dftables"
	@echo "... pcre"
	@echo "... pcre_static"
	@echo "... lua"
	@echo "... lua_static"
	@echo "... expat"
	@echo "... expat_static"
	@echo "... xerces-c_3"
	@echo "... xerces-c_3_static"
	@echo "... SILLY"
	@echo "... SILLY_static"
	@echo "... glew"
	@echo "... glew_static"
	@echo "... glfw"
	@echo "... glfw_static"
	@echo "... glm"
	@echo "... toluapp"
	@echo "... toluapp_static"
	@echo "... ode"
	@echo "... ode_static"
	@echo "... cppunit"
	@echo "... cppunit_static"
	@echo "... NL"
	@echo "... NL_static"
	@echo "... gne"
	@echo "... gne_static"
	@echo "... cal3d"
	@echo "... cal3d_converter"
	@echo "... cal3d_static"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

