# makefile for GCC compilers in various platforms.

CPP                  = g++
CC                   = gcc

COMMONFLAGS          = -Wall -Iinclude -pipe -fPIC

ifdef ARCH
COMMONFLAGS         += -arch $(ARCH)
LDFLAGS             += -arch $(ARCH)
endif

DEBUGFLAGS           = $(COMMONFLAGS) -D_DEBUG 
OPTIMIZEFLAGS        = $(COMMONFLAGS) -O3 -s

DEBUGMODE            = true
HAWKNL_INCLUDE_PATH  = /Users/david/development/ext/src/HawkNL1.68/include
BOOST_INCLUDE_PATH   = /Users/david/development/delta3d/ext/inc

ifdef DEBUGMODE
CPPFLAGS             = $(DEBUGFLAGS)
CFLAGS               = $(DEBUGFLAGS)
LIB_STATIC_NAME      = libgne.a
else
LDFLAGS             += -s
LIB_STATIC_NAME      = libgne.a
CPPFLAGS             = $(OPTIMIZEFLAGS)
CFLAGS               = $(OPTIMIZEFLAGS)
endif

ifdef BOOST_INCLUDE_PATH
CPPFLAGS            += -I$(BOOST_INCLUDE_PATH)
endif

ifdef HAWKNL_INCLUDE_PATH
CPPFLAGS            += -I$(HAWKNL_INCLUDE_PATH)
endif

ifdef HAWKNL_LIBRARY_PATH
LDFLAGS             = -L$(HAWKNL_LIBRARY_PATH)
endif

ifdef OLD_CPP
CPPFLAGS            += -DOLD_CPP
endif

EXAMPLE_CPP          = $(wildcard examples/*/*.cpp)

EXAMPLE_O            = $(EXAMPLE_CPP:.cpp=.o)

LIB_CPP              = $(wildcard src/*.cpp)
LIB_C                = $(wildcard src/*.c)

LIB_CPP_O            = $(LIB_CPP:.cpp=.o)
LIB_C_O              = $(LIB_C:.c=.o)
LIB_O                = $(LIB_CPP_O) $(LIB_C_O)

DEPENDENCIES         = $(notdir $(LIB_O:.o=.d))

VPATH                = $(dir $(EXAMPLE_CPP))
